### ISSUE TITLE
Лагает реакция бота на сообщения от пользователя. 

### ISSUE THREAD

**Issue by dvsmasters** [beevel2/chat_accepter#11]
После обновы появился какой-то баг. Пользователь нажимает на кнопку полученную в сообщение Взаимодействие 1, однако ничего не происходит, 6 раз нажал на кнопку, прошла минута(таймер) на отправку сообщения Взаимодействие 2, оно его прислало, и только после него прислало сообщение 4. Хотя Взаимодействие 2 вообще не должно было быть прислано.

**Comment by beevel2** [comment]
"Сообщение 4" это какое?
