### ISSUE TITLE
Доработка Статистика, Удаление каналов, Очистка сообщений.

### ISSUE THREAD

**Issue by dvsmasters** [beevel2/chat_accepter#6]
1.Добавить статистику в меню канала:
Пользователей всего: 12345 
Взаимодействовали: 1234 (у нас же у каждого флаг есть true/false) по нему посчитать сколько взаимодействий с ботом.
Заблокировало: 123 

В меню канала.

2. **Добавить возможность админам удалять каналы**. На клавиатуру управления каналом добавить кнопку "Удалить канал"
Бот спрашивает:  Вы уверены в удалении канала [НАЗВАНИЕ]. Все данные об этом канале будут безвозвратно удалены. Кнопки:
**Подтвердить
Отменить**

3.Необходимо добавить очистку сообщений, сейчас предусмотрена только замена. Например я добавил сообщения 1, 2 и 3. Но 3 мне вообще не нужно, я его не могу очистить, только заменить на другое. Очистку приходится делать через бд.
Я думаю можно после нажатия на сообщение которое хотим редактировать, добавить внизу кнопку Очистить на клавиатуре или inline, которая просто удалит его.
Если админ нажал на кнопку Очистить, то мы показываем это сообщение и просим подтвердить.
Бот пишет, подтвердите удаление сообщения: "Текст сообщения".
Кнопки: **Подтвердить, Отменить.**

**Comment by beevel2** [comment]
3 done

**Comment by beevel2** [comment]
2 done

**Comment by beevel2** [comment]
#8 Updates done
